PLATFORM_STANDARDIZATION = {
    "A&E Crime Central": "A&E Crime Central",
    "ALLBLK": "ALLBLK",
    "ALLBLK Amazon channel": "ALLBLK",
    "AMC": "AMC",
    "AMC Plus Apple TV Channel": "AMC+",
    "AMC+": "AMC+",
    "ARROW": "ARROW",
    "Acorn TV": "Acorn TV",
    "Amazon Prime Video": "Amazon Prime Video",
    "Amazon Prime Video with Ads": "Amazon Prime Video",
    "Apple TV+": "Apple TV+",
    "AsianCrush": "AsianCrush",
    "BBC America": "BBC America",
    "BET+": "BET+",
    "BritBox": "BritBox",
    "Chai Flicks": "Chai Flicks",
    "Cinemax": "Cinemax",
    "Cineverse": "Cineverse",
    "Cohen Media": "Cohen Media",
    "Criterion Channel": "Criterion Channel",
    "Crunchyroll": "Crunchyroll",
    "Cultpix": "Cultpix",
    "Curiosity Stream": "Curiosity Stream",
    "CuriosityStream Apple TV Channel": "Curiosity Stream",
    "Dekkoo": "Dekkoo",
    "Disney Plus": "Disney+",
    "DisneyNOW": "Disney+",
    "Epix": "Epix",
    "Eros Now Select": "Eros Now Select",
    "FXNow": "FXNow",
    "Fandor": "Fandor",
    "Film Movement Plus": "Film Movement Plus",
    "FilmBox+": "FilmBox+",
    "Flix Premiere": "Flix Premiere",
    "FlixFling": "FlixFling",
    "Freeform": "Freeform",
    "Full Moon": "Full Moon",
    "GuideDoc": "GuideDoc",
    "HBO Max": "Max",
    "Hallmark Movies Now": "Hallmark Plus",
    "Here TV": "Here TV",
    "Hi-YAH": "Hi-YAH",
    "HiDive": "HiDive",
    "History Vault": "History Vault",
    "Hoichoi": "Hoichoi",
    "Hoopla": "Hoopla",
    "Hulu": "Hulu",
    "IFC Films Unlimited": "IFC Films Unlimited",
    "IndieFlix": "IndieFlix",
    "Kanopy": "Kanopy",
    "Kino Film Collection": "Kino Film Collection",
    "Klassiki": "Klassiki",
    "Kocowa": "Kocowa",
    "Lifetime Movie Club": "Lifetime Movie Club",
    "MGM+": "MGM+",
    "MUBI": "MUBI",
    "MZ Choice": "MZ Choice",
    "Magellan TV": "Magellan TV",
    "Max Amazon Channel": "Max",
    "Metrograph": "Metrograph",
    "Midnight Pulp": "Midnight Pulp",
    "NBC": "NBC",
    "Netflix": "Netflix",
    "Netflix basic with Ads": "Netflix",
    "Night Flight Plus": "Night Flight Plus",
    "OVID": "OVID",
    "OnDemandKorea": "OnDemandKorea",
    "PBS Masterpiece Amazon Channel": "PBS Masterpiece",
    "Paramount Plus Apple TV Channel": "Paramount+",
    "Paramount+": "Paramount+",
    "Peacock": "Peacock",
    "Pure Flix": "Pure Flix",
    "Rakuten Viki": "Rakuten Viki",
    "RetroCrush Amazon Channel": "RetroCrush",
    "Retrocrush": "RetroCrush",
    "Revry": "Revry",
    "Screambox": "Screambox",
    "ScreenPix": "ScreenPix",
    "Shahid VIP": "Shahid VIP",
    "ShortsTV Amazon Channel": "ShortsTV",
    "Shudder": "Shudder",
    "Starz": "Starz",
    "Strand Releasing": "Strand Releasing",
    "Sun Nxt": "Sun Nxt",
    "Sundance Now": "Sundance Now",
    "TBS": "TBS",
    "TCM": "TCM",
    "TNT": "TNT",
    "Troma NOW": "Troma NOW",
    "UP Faith & Family": "UP Faith & Family",
    "USA Network": "USA Network",
    "VIX": "VIX",
    "YouTube": "YouTube",
    "aha": "aha",
    "fuboTV": "fuboTV",
    "iQIYI": "iQIYI",
    "tru TV": "tru TV"
}

POPULAR_PLATFORMS = [
    "Netflix",
    "Amazon Prime Video",
    "Disney+",
    "Hulu",
    "Max",
    "Apple TV+",
    "Peacock",
    "Paramount+",
    "YouTube",
    "Crunchyroll",
    "HBO Max",
    "BBC America",
    "AMC+",
    "AMC",
    "Shudder",
    "Starz",
    "Criterion Channel",
    "MGM+",
    "MUBI",
    "Kanopy",
    "Curiosity Stream",
    "Acorn TV",
    "BritBox",
    "RetroCrush",
    "fuboTV",
    "HiDive",
    "AsianCrush",
    "VIX",
    "iQIYI",
    "Lifetime Movie Club",
    "Sundance Now",
    "Pure Flix",
    "ScreenPix",
    "ShortsTV",
    "Night Flight Plus",
    "Dekkoo",
    "IndieFlix",
    "Metrograph",
    "Troma NOW",
    "Cinemax",
    "Full Moon",
    "Midnight Pulp",
    "TBS",
    "TNT",
    "USA Network",
    "tru TV",
    "History Vault",
    "Hallmark Plus",
    "Epix",
    "GuideDoc",
    "Hoopla",
    "PBS Masterpiece",
    "Freeform",
    "BET+",
    "Cineverse",
    "FilmBox+",
    "Film Movement Plus",
    "Fandor",
    "Kino Film Collection",
    "Klassiki",
    "Kocowa",
    "ALLBLK",
    "ARROW",
    "Chai Flicks",
    "Cohen Media",
    "Cultpix",
    "Hoichoi",
    "Magellan TV",
    "Here TV",
    "Screambox",
    "Sundance Now",
    "Shahid VIP",
    "UP Faith & Family",
    "Strand Releasing",
    "Eros Now Select",
    "aha"
]
